site_name: twitter-news-bot

site_url: https://arnavmarda.github.io/twitter-news-bot/

theme:
  name: "material"
  palette:
    scheme: slate
    primary: black
    accent: cyan
  logo: logo.png
  font:
    text: Victor
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
    - navigation.footer
    - instant
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Getting Started: index.md
  - Installation: installation.md
  - Using Github Actions: github-actions.md
  - API Reference:
    - News Finder: newsfinder.md
    - Tweeter: tweeter.md
    - Twitter News Bot: twitternewsbot.md
  - CLI Reference:
    - Commands: commands.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          path: [twitternewsbot]
          options:
            members_order: source
            docstring_style: numpy
            docstring_section_style: spacy
            separate_signature: true
            filters: 
              - "!^__"
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arnavmarda
  generator: false

copyright: Copyright &copy; 2023 Arnav Marda

repo_url: https://github.com/arnavmarda/twitter-news-bot

extra_css:
  - stylesheets/extras.css

markdown_extensions:
  - attr_list
  - mkdocs-click
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true